### ISSUE TITLE
Instant crash if open folder or add active/all files is clicked.

### ISSUE THREAD

**Issue by BerraDev** [perlowgren/Djynn#1]
Instant crash if open folder or add active/all files is clicked.

Once a new project was started it was fine to click these, but without a project it caused an instant crash.

These options crashed Geany upon click when no project was created yet:

> Open Directory
> Add Active Files
> Add All Open Files

```
Linux arch 3.16.3-1-ARCH #1 SMP PREEMPT Wed Sep 17 21:54:13 CEST 2014 x86_64 GNU/Linux

cmake version 3.0.2

geany 1.24.1 (built on 2014-04-16 with GTK 2.24.23, GLib 2.40.0)

Djynn 0.2 ( cloned from latest git today )
```

**Comment by perlowgren** [comment]
Sorry for late reply, the bug is fixed.
